version: 2

jobs:
  unit-py27:
    docker:
    - image: python:2.7
      environment: &unit_env
        TERM: linux
        TERMINFO: /etc/terminfo
    working_directory: /workspace
    steps: &unit_steps
      - checkout
      - restore_cache:
          keys:
            - temboard-toolkit-{{ .Branch }}
            - temboard-toolkit-master
      - run:
          name: Python lint and tests
          command: |
            set -x
            pip install --upgrade --requirement requirement-ci.txt
            git diff --check $(git merge-base origin/master $CIRCLE_SHA1)..$CIRCLE_SHA1
            flake8 .
            pytest tests/
            PYTHONPATH=tests/ python -m sampleproject.toolkit.proctitle
            PYTHONPATH=tests/ python -c 'from sampleproject.toolkit.proctitle import test_main; test_main()'
            codecov
      - save_cache:
          key: temboard-toolkit-{{ .Branch }}
          paths:
            - "~/.cache/pip/"

  unit-py36:
    docker:
    - image: python:3.6
      environment: *unit_env
    working_directory: /workspace
    steps: *unit_steps


workflows:
  version: 2
  pipeline:
    jobs:
    - unit-py27
    - unit-py36
